version: "3"
services:
  base-gpu-container: # Base service with shared elements
    image: gpu-image
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  container-1:
    extends:
      service: base-gpu-container
    deploy:
      resources:
        limits:
          cpus:   "8"  # May be able to reduce
          memory: "40G" # May be able to reduce
    volumes:
      - /mnt/docker_home:/home
    ports:
      - "2222:22"
    command: >
      /usr/sbin/sshd -D&&
      tail -f /dev/null
    restart: always

  container-2:
    extends:
      service: base-gpu-container
    deploy:
      resources:
        limits:
          cpus:   "6"  # Example if workload is lighter
          memory: "30G"
    volumes:
      - /mnt/docker_home_2:/home
    ports:
      - "2223:22"
    command: >
      /usr/sbin/sshd -D&&
      tail -f /dev/null
    restart: always